In [18]:
import pandas as pd

In [ ]:
# df = pd.read_parquet("part-00000-1dc0d1bc-3cdc-4fa2-a1dc-c9597cd083eb-c000.snappy.parquet")

In [ ]:
# df.head(5)

,review_id,tmdb_id,imdb_id,author,content,rating,source_system,created_at,ingestion_id
0,000524abf6de59d91f3e4a4375ec8415cc5a9cdf1fe595...,None,tt27543632,Maoz_Shechter,"For the first hour of the movie, I honestly di...",7.0,imdb,2026-01-13,7991a775-a677-4a81-8eef-b0a86f2bc34f
1,000a465558f22ae39464a9830ce91dbcd7786a76ab60ab...,None,tt7181546,HOTSHOT100Real,"I actual like this film a lot, this film is no...",7.0,imdb,2025-06-22,cf022852-97f7-4860-ac88-032094e17a6e
2,002c15fdae45738c4c9a43d5db9a73b2b00c5ddd4a19fa...,None,tt15239678,madanmarwah,This movie is a spell binding experience. It i...,9.0,imdb,2024-04-24,54797871-88dd-41ed-acd9-71efdd01f1ab
3,00324f24c88d54a8b16f82678af5f73de679da98136071...,None,tt0082010,richard_wright,An American Werewolf in London is a perfect ex...,9.0,imdb,2003-02-27,eb7b0ccc-46a3-41cc-81ef-ad53d29c48ee
4,00356c43c1324f1f636c22fe9926ed43b1d843360c9c40...,None,tt15940132,claudiusabel,This is the second movie i've watched from Ala...,3.0,imdb,2026-03-09,4ef2d39e-0667-4bf3-a904-13a4db2eb0c1

In [ ]:
# df2 = pd.read_parquet("part-00000-2785690b-ff9f-408f-b1bf-8eb8d2b2b92b-c000.snappy.parquet")
# df2.head(5)

,ingestion_id,review_id,tmdb_id,imdb_id,author,content,rating,source_system,created_at,predicted_sentiment,sentiment_confidence
0,bd1c886b-2d7a-497a-a193-93c75dba73e5,000524abf6de59d91f3e4a4375ec8415cc5a9cdf1fe595...,None,tt27543632,Maoz_Shechter,"For the first hour of the movie, I honestly di...",7.0,imdb,2026-01-13,1.0,0.790703
1,e1f36d0c-e839-4dab-975b-116408985e9b,002c15fdae45738c4c9a43d5db9a73b2b00c5ddd4a19fa...,None,tt15239678,madanmarwah,This movie is a spell binding experience. It i...,9.0,imdb,2024-04-24,1.0,0.984875
2,e976ad3a-f2e5-467f-87f6-0793f209d62d,00356c43c1324f1f636c22fe9926ed43b1d843360c9c40...,None,tt15940132,claudiusabel,This is the second movie i've watched from Ala...,3.0,imdb,2026-03-09,0.0,0.624059
3,961ef568-e058-4125-b974-9a8873f85017,00435bd9efbba5d93cd99e0905406c505c5fa2f6269822...,None,tt15398776,jamkafka,I have always loved biopics especially when I ...,8.0,imdb,2024-06-20,1.0,0.934672
4,986a06e6-d077-4328-a19a-27f17b9036a4,00448ca2411ce6bb93ec8a1cab9b0d22b559be878078d7...,None,tt30144839,andrewvmcdermot,Horrible from start to finish. Clearly made to...,2.0,imdb,2025-10-09,0.0,0.589789

In [ ]:
# df3 = pd.read_json("raw_reviews_part_1 (1).jsonl", lines=True)
# import json

# payload_df = pd.json_normalize(df3["raw_payload"])

In [14]:
payload_df

,movie_id,author,rating,date,title,content
0,tt27552099,eddie_baggins,4.0,2026-04-09,None,"Recently making its way onto Hulu/Disney+, Ben..."
1,tt27552099,solinsbiosalong,NaN,2026-04-08,None,I feel violated and heartbroken.\n\nHow could ...
2,tt27552099,danieljfarthing,8.0,2026-04-07,None,"Daft comic shoot-em-up ""Mike & Nick & Nick & A..."
3,tt27552099,dcj2,NaN,2026-04-07,None,"Really wanted to like this, but boy, what a le..."
4,tt27552099,pzrqy,5.0,2026-04-06,None,"I wanted an easy and fun watch, and this one s..."
...,...,...,...,...,...,...
86,tt27552099,tsvetan_mehochev,2.0,2026-03-27,None,This has got to be one of dumbest if not the d...
87,tt27552099,attilalengyel-78684,7.0,2026-03-27,None,This is a kind of movie I like so much when I ...
88,tt27552099,diemarxens,8.0,2026-03-27,None,Don´t take it too serious as obvious the movie...
89,tt27552099,davidbleavitt,7.0,2026-03-27,None,"So, Mike and Nick and Nick and Alice.\n\nA mos..."
90,tt27552099,reefpye,8.0,2026-03-27,None,I was pleasantly surprised with this movie. A ...

In [ ]:
# df4 = pd.read_json("raw_reviews_part_1 (2).jsonl", lines=True)

# payload_df2 = pd.json_normalize(df4["raw_payload"])

In [ ]:
# payload_df2

,movie_id,author,rating,date,title,content
0,tt27552099,solinsbiosalong,NaN,2026-04-08,None,I feel violated and heartbroken.\n\nHow could ...
1,tt27552099,danieljfarthing,8.0,2026-04-07,None,"Daft comic shoot-em-up ""Mike & Nick & Nick & A..."
2,tt27552099,dcj2,NaN,2026-04-07,None,"Really wanted to like this, but boy, what a le..."
3,tt27552099,pzrqy,5.0,2026-04-06,None,"I wanted an easy and fun watch, and this one s..."
4,tt27552099,wckedmnkey-828-307083,7.0,2026-04-06,None,"This is and enjoyable, lighthearted sci-fi com..."
...,...,...,...,...,...,...
85,tt27552099,tsvetan_mehochev,2.0,2026-03-27,None,This has got to be one of dumbest if not the d...
86,tt27552099,attilalengyel-78684,7.0,2026-03-27,None,This is a kind of movie I like so much when I ...
87,tt27552099,diemarxens,8.0,2026-03-27,None,Don´t take it too serious as obvious the movie...
88,tt27552099,davidbleavitt,7.0,2026-03-27,None,"So, Mike and Nick and Nick and Alice.\n\nA mos..."
89,tt27552099,reefpye,8.0,2026-03-27,None,I was pleasantly surprised with this movie. A ...

In [19]:
data = pd.read_csv("output.csv")

In [22]:
data["label"] = data["rating"].apply(
    lambda x: 1.0 if x >= 7.0 else(0.0 if pd.notna(x) else None)
)

In [23]:
data.head(5)

,review_id,imdb_id,content,rating,source_system,label
0,000524abf6de59d91f3e4a4375ec8415cc5a9cdf1fe595...,tt27543632,"For the first hour of the movie, I honestly di...",7.0,imdb,1.0
1,000a465558f22ae39464a9830ce91dbcd7786a76ab60ab...,tt7181546,"I actual like this film a lot, this film is no...",7.0,imdb,1.0
2,002c15fdae45738c4c9a43d5db9a73b2b00c5ddd4a19fa...,tt15239678,This movie is a spell binding experience. It i...,9.0,imdb,1.0
3,00356c43c1324f1f636c22fe9926ed43b1d843360c9c40...,tt15940132,This is the second movie i've watched from Ala...,3.0,imdb,0.0
4,00448ca2411ce6bb93ec8a1cab9b0d22b559be878078d7...,tt30144839,Horrible from start to finish. Clearly made to...,2.0,imdb,0.0

In [48]:
data["label"].value_counts(normalize=True)

label
1.0    0.674941
0.0    0.325059
Name: proportion, dtype: float64

In [50]:
data.groupby("source_system")["label"].value_counts(normalize=True)

source_system  label
imdb           1.0      0.674996
               0.0      0.325004
tmdb           1.0      0.600000
               0.0      0.400000
Name: proportion, dtype: float64

In [54]:
data_clean = data.dropna(subset=["content", "label"])
X = data_clean["content"]
y = data_clean["label"]

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=10000,
    stop_words="english"
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [66]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"  # quan trọng vì data hơi lệch
)

model.fit(X_train_vec, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [67]:
y_pred = model.predict(X_test_vec)

In [68]:
print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

label
1.0    0.674938
0.0    0.325062
Name: proportion, dtype: float64
label
1.0    0.67495
0.0    0.32505
Name: proportion, dtype: float64

In [69]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.77      0.87      0.81      4408
         1.0       0.93      0.88      0.90      9153

    accuracy                           0.87     13561
   macro avg       0.85      0.87      0.86     13561
weighted avg       0.88      0.87      0.87     13561

In [ ]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

array([[3813,  595],
       [1142, 8011]])

In [73]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC(
    class_weight="balanced",  # xử lý imbalance
    max_iter=2000
)

svm_model.fit(X_train_vec, y_train)

LinearSVC(class_weight='balanced', max_iter=2000)

In [75]:
y_pred_svm = svm_model.predict(X_test_vec)

In [76]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_svm))

              precision    recall  f1-score   support

         0.0       0.76      0.83      0.80      4408
         1.0       0.92      0.88      0.90      9153

    accuracy                           0.86     13561
   macro avg       0.84      0.85      0.85     13561
weighted avg       0.87      0.86      0.86     13561